export const tree = [
  {
    name: 'Web Applications',
    type: 'folder',
    route: 'web-applications',
    content: [
      {
        name: 'Wedding RSVP',
        date: 'July 2021',
        icon: '/img/icons/wedding.jpg',
        type: 'project',
        content: '',
        techStack: ['Django'],
        deployment: ['Heroku'],
        url: 'none',
      },
      {
        name: 'ElPolloPaulino',
        date: 'February 2023',
        icon: '/img/icons/paulino.png',
        type: 'project',
        content: '',
        techStack: ['MongoDB', 'Express', 'React', 'Node'],
        deployment: ['Heroku', 'Netlify'],
        url: 'https://www.elpollopaulino.com',
      },
      {
        name: 'Cisna - SmartHome',
        date: 'March 2024',
        icon: '/img/icons/cisna.png',
        type: 'project',
        content: '',
        techStack: ['Next.js'],
        deployment: ['Vercel'],
        url: 'https://www.cisnahome.es',
      },
      {
        name: 'TropycalCBD',
        date: 'April 2024',
        icon: '/img/icons/tropycal.png',
        type: 'project',
        content: '',
        techStack: ['Shopify'],
        deployment: ['Shopify'],
        url: 'https://www.tropycalcbd.com',
      },
      {
        name: 'RouteForecast',
        date: 'August 2023',
        icon: '/img/icons/routeforecast.jpg',
        type: 'project',
        content: '',
        techStack: ['MongoDB', 'Express', 'React', 'Node'],
        deployment: ['Heroku', 'Netlify'],
        url: 'https://www.routeforecast.app',
      },
      {
        name: 'Personal Portfolio',
        date: 'April 2024',
        icon: '/img/icons/pablooses.jpg',
        type: 'project',
        content: '',
        techStack: ['Next.js'],
        deployment: ['Vercel'],
        url: 'https://www.pablo-oses.com',
      },
    ],
  },

  {
    name: 'Curriculum Vitae',
    type: 'pdf',
    content: '/pdf/curriculumvitae.pdf',
    route: 'curriculum-vitae',
  },
  {
    name: 'Who Am I',
    type: 'text',
    content:
      '### Who Am I?\n\nHello! My name is **Pablo**, and I am a **Full Stack Developer** with a keen interest in software engineering. I’m ready to gain practical experience and expand my knowledge. While I’m relatively new to the professional scene, I’ve been developing my skills not only through personal projects but also through client projects.\n\n### My Focus\n\nI focus on **SOLID principles** and design patterns, aiming to write clean, efficient, and scalable code. I enjoy using technologies like **Next.js** to build applications that are centered around the user.\n\n### Growth Mindset\n\nI’m a quick learner with a growth mindset, always ready to pick up new skills and stay updated with evolving industry trends.\n\n### Looking for Opportunities\n\nI’m actively looking for opportunities where I can contribute and learn from experienced professionals. Let’s connect and discuss how I can add value to your projects while gaining valuable real-world experience. Looking forward to our conversation!',
    route: 'who-am-i',
  },
  {
    name: 'Contact Me',
    type: 'contact',
    content: '**Lorem** ipsum dolor sit amet.',
    route: 'contact',
  },
];
